before:
  hooks:
    - make clean

builds:
  - binary: terraform-provider-snowflake_{{ .Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
<<<<<<< HEAD
      - "-w -s -X github.com/viostream/terraform-provider-snowflake/util.GitSha={{.Commit}} -X github.com/viostream/terraform-provider-snowflake/util.Version={{.Version}} -X github.com/viostream/terraform-provider-snowflake/util.Dirty=false -X github.com/viostream/terraform-provider-snowflake/util.Release=true"
=======
      - "-w -s -X github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version.GitSha={{.Commit}} -X github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version.Version={{.Version}} -X github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version.Dirty={{.Env.DIRTY}}"
>>>>>>> 7dd55fa02ff8b69235d11375c3fb5f2028e5146b

archive:
  files:
    - none*

release:
  prerelease: false

env_files:
  github_token: ~/.config/goreleaser/github_token
